
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnnouncementTable
    {
        public int AunId { get; set; }
        public int GrpId { get; set; }
        public int SenderId { get; set; }

        [Required(ErrorMessage = "The announcement can not be null.")]
        public string Cont { get; set; }
        public System.TimeSpan Time { get; set; }

        public string FormattedTime => Time.ToString(@"hh\:mm");
        public Nullable<System.DateTime> Date { get; set; }

        public virtual GroupMemberTable GroupMemberTable { get; set; }
        public virtual GroupTable GroupTable { get; set; }
    }
}