//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbookTable
    {
        public int EbookId { get; set; }
        public string EbookName { get; set; }
        public string EbookDescp { get; set; }
        public string Author { get; set; }
        public string EbookPath { get; set; }
        public string EbookImgPath { get; set; }
    }
}
