//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackTable
    {
        public int FeedbackId { get; set; }
        public int Rating { get; set; }
        public string cont { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
