//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingTable
    {
        public int MeetingId { get; set; }
        public string MeetingLink { get; set; }
        public int CreatorId { get; set; }
        public int GrpId { get; set; }
    
        public virtual GroupMemberTable GroupMemberTable { get; set; }
        public virtual GroupTable GroupTable { get; set; }
    }
}
