
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ToDoTable
    {
        public int ToDoId { get; set; }
        public int Uid { get; set; }

        [Required(ErrorMessage = "The Todo field is required.")]
        public string Cont { get; set; }
        public bool isDone { get; set; }

        public virtual UserTable UserTable { get; set; }
    }
}