
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.GroupMemberTables = new HashSet<GroupMemberTable>();
            this.GroupTables = new HashSet<GroupTable>();
            this.ToDoTables = new HashSet<ToDoTable>();
        }

        public int Uid { get; set; }

        [Required(ErrorMessage = "Enter your Full Name")]
        [Display(Name = "Full Name")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Enter your Email address")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Please enter a valid Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter a UserName")]
        [Display(Name = "User Name")]
        [StringLength(maximumLength: 10, MinimumLength = 5, ErrorMessage = "User Name Length Must Be Max 10 & Min 5")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Enter a strong Passward")]
        [Display(Name = "Passward")]
        [DataType(DataType.Password)]
        public string Pwd { get; set; }

        [Required(ErrorMessage = "Enter a strong Passward")]
        [Compare("Pwd", ErrorMessage = "Password does not match")]
        [Display(Name = "Confirm Passward")]
        [DataType(DataType.Password)]
        public string rePwd { get; set; }
        public bool UserStatus { get; set; }
        public string UserImgPath { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMemberTable> GroupMemberTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTable> GroupTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoTable> ToDoTables { get; set; }
        public virtual ICollection<FeedBackTable> FeedBackTables { get; set; }
    }
}