//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTalk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnityTalkEntities8 : DbContext
    {
        public UnityTalkEntities8()
            : base("name=UnityTalkEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<AnnouncementTable> AnnouncementTables { get; set; }
        public virtual DbSet<EbookTable> EbookTables { get; set; }
        public virtual DbSet<FeedBackTable> FeedBackTables { get; set; }
        public virtual DbSet<FileTable> FileTables { get; set; }
        public virtual DbSet<GroupImgTable> GroupImgTables { get; set; }
        public virtual DbSet<GroupMemberTable> GroupMemberTables { get; set; }
        public virtual DbSet<GroupTable> GroupTables { get; set; }
        public virtual DbSet<MeetingTable> MeetingTables { get; set; }
        public virtual DbSet<MessageTable> MessageTables { get; set; }
        public virtual DbSet<ToDoTable> ToDoTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
